# Project: parser
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = incompleted/charcode.o incompleted/error.o incompleted/main.o incompleted/parser.o incompleted/reader.o incompleted/scanner.o incompleted/token.o
LINKOBJ  = incompleted/charcode.o incompleted/error.o incompleted/main.o incompleted/parser.o incompleted/reader.o incompleted/scanner.o incompleted/token.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = parser.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

incompleted/charcode.o: incompleted/charcode.c
	$(CC) -c incompleted/charcode.c -o incompleted/charcode.o $(CFLAGS)

incompleted/error.o: incompleted/error.c
	$(CC) -c incompleted/error.c -o incompleted/error.o $(CFLAGS)

incompleted/main.o: incompleted/main.c
	$(CC) -c incompleted/main.c -o incompleted/main.o $(CFLAGS)

incompleted/parser.o: incompleted/parser.c
	$(CC) -c incompleted/parser.c -o incompleted/parser.o $(CFLAGS)

incompleted/reader.o: incompleted/reader.c
	$(CC) -c incompleted/reader.c -o incompleted/reader.o $(CFLAGS)

incompleted/scanner.o: incompleted/scanner.c
	$(CC) -c incompleted/scanner.c -o incompleted/scanner.o $(CFLAGS)

incompleted/token.o: incompleted/token.c
	$(CC) -c incompleted/token.c -o incompleted/token.o $(CFLAGS)
